name: MineTorNodes

on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '3 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: tor
      - name: Create temp dir
        run: |-
          mkdir -p temp
      - name: Pull the Block List
        run: |-
          curl "https://www.dan.me.uk/torlist/?exit" -o ./temp/exit-nodes.txt || true
          ./scripts/collapse-ip-list.py ./temp/exit-nodes.txt "https://check.torproject.org/torbulkexitlist" > exit-nodes.txt
      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
